"use client";

import { Download } from "lucide-react";

export function ExportRoadmapButton() {
  const handleExport = async () => {
    try {
      const [profileRes, appsRes, uniRes] = await Promise.all([
        fetch("/api/user/profile").then((r) => r.json()),
        fetch("/api/applications").then((r) => r.json()),
        fetch("/api/universities").then((r) => r.json()),
      ]);

      const user = profileRes.user;
      const apps = appsRes.applications ?? [];
      const unis = (uniRes.universities ?? []).slice(0, 10);

      let text = "RIBRIZ — Application Roadmap\n";
      text += "=" .repeat(40) + "\n\n";

      if (user) {
        text += `Student: ${user.name}\n`;
        text += `Email: ${user.email}\n`;
        if (user.academicProfile) {
          text += `GPA: ${user.academicProfile.gpa}/${user.academicProfile.gpaScale === "scale_4" ? "4" : "10"}\n`;
        }
        text += "\n";
      }

      text += "TOP UNIVERSITY MATCHES\n";
      text += "-".repeat(40) + "\n";
      for (const u of unis) {
        text += `  ${u.matchScore}% — ${u.name} (${u.country})\n`;
        text += `         ${u.courseName}\n`;
        text += `         Deadline: ${u.deadline}\n\n`;
      }

      if (apps.length > 0) {
        text += "\nAPPLICATIONS\n";
        text += "-".repeat(40) + "\n";
        for (const a of apps) {
          text += `  ${a.program.university.name} — ${a.program.name}\n`;
          text += `  Status: ${a.status} | Match: ${a.matchScore ?? "N/A"}%\n\n`;
        }
      }

      text += "\nGenerated by RIBRIZ on " + new Date().toLocaleDateString() + "\n";

      const blob = new Blob([text], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `ribriz-roadmap-${new Date().toISOString().slice(0, 10)}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      // Silently fail
    }
  };

  return (
    <button
      onClick={handleExport}
      className="btn-secondary px-4 py-2.5 text-sm flex items-center gap-2"
    >
      <Download size={14} />
      Export Roadmap
    </button>
  );
}
